name: GH-Pages CI/CD

permissions:
  contents: read
  id-token: write

on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  build-push-registry:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GH_BOT_PAT }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.OPS_GITHUB_ROLE }}
          aws-region: ${{ secrets.ORG_AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Build Container Image and push to ECR
        env:
          ECR_REGISTRY: ${{ secrets.OPS_PRIVATE_ECR_REGISTRY }}
          ECR_REPOSITORY: gh-pages
          GH_TAG: ${{ github.sha }}
        run: |
          docker build -t "${ECR_REGISTRY}/${ECR_REPOSITORY}:${GH_TAG}" -f Dockerfile .
          docker tag "${ECR_REGISTRY}/${ECR_REPOSITORY}:${GH_TAG}" "${ECR_REGISTRY}/${ECR_REPOSITORY}:latest"
          docker push "${ECR_REGISTRY}/${ECR_REPOSITORY}:${GH_TAG}"
          docker push "${ECR_REGISTRY}/${ECR_REPOSITORY}:latest"


  edit-image-tag:
    needs: build-push-registry
    name: Deliver to K8S
    runs-on: ubuntu-latest
    steps:
      - name: Clone live environments repo
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.SAAS_LIVE_ENVIRONMENTS_REPOSITORY }}
          ref: main
          token: ${{ secrets.GH_BOT_PAT }}

      - name: Edit image tag in live-environments
        env:
          TAG: ${{ github.sha }}
          ECR_REGISTRY: ${{ secrets.OPS_PRIVATE_ECR_REGISTRY }}
          ECR_REPOSITORY: gh-pages
        working-directory: ./

        run: |
          git config --global user.name ${{ vars.GH_BOT_USERNAME }}
          git config --global user.email ${{ vars.GH_BOT_EMAIL }}
          cd aws/sources/staging/gh-pages
          yq -i "select(document_index == 0).spec.template.spec.containers[0].image = \"${ECR_REGISTRY}/${ECR_REPOSITORY}:${TAG}\"" values.yaml
          git commit -am "change gh-pages image tag to $TAG"
          git push
